### ISSUE TITLE
Does this support animated SVGs?

### ISSUE THREAD

**Issue by quakeulf** [mono/SkiaSharp.Extended#10]
Please let me know.

Thank you very much in advance for helping me out.

**Comment by mattleibow** [comment]
Not at this time. Right now, the SVG is converted to a `SKPicture` as it is parsed - which is a static drawing.

**Comment by quakeulf** [comment]
Ok, thank you for letting me know.

However, it still seems according to the demo that animations work and that the syntax for determining the shapes are interchangeable with SVGs. At least interpolation between four differently shaped objects work, so I am guessing colour change, rotation, scale and position will work too.

**Comment by MinkyuKang** [comment]
Do you have plan to support this?

**Comment by mattleibow** [comment]
Not in the near future. The interpolation example, (https://github.com/mono/SkiaSharp.Extended/tree/master/SkiaSharp.Extended#skpathinterpolation) is totally separate and is just basic interpolation between two `SKPath` objects through the use of a new path. The animation is then done via a stepping manually through all the paths in the draw method.
