### ISSUE TITLE
[QUESTION] Can we get a new nuget release?

### ISSUE THREAD

**Issue by ryanalford-suzy** [mono/SkiaSharp.Extended#107]
There have been plenty of great additions to this repo over the last year, but it's been almost 3 years since the last nuget package release.

Would it be possible to get another release?

**Comment by ryanalford-suzy** [comment]
@timvandenhof we ended up moving to using  https://github.com/wieslawsoltes/Svg.Skia. Seems the current library is pretty much depreciated, and the new library is not.

**Comment by mattleibow** [comment]
The library that was in this repo is like a 3 color paint set compared to all the colors in the universe. Svg.Skia is pretty much the most complete SVG parsing library.

The library in this repo had a good run and did the basics, but it is time to embrace the work done by geniuses.
