### ISSUE TITLE
[FEATURE] Overriding SVG Style (Or just stroke/fill colors)

### ISSUE THREAD

**Issue by romen-h** [mono/SkiaSharp.Extended#109]
**Is your feature request related to a problem? Please describe.**

I would like to override the stroke and fill colors of elements after the SVG file has been loaded.
There is no API to do this, and `SKPicture` does not seem to have any public API to modify the colors in the cached drawing commands.

**Describe the solution you'd like**

I would like to see some kind of callback to provide custom SVG styles or SKPaint as each element is "drawn" to the SKPicture.

**Describe alternatives you've considered**

I am also looking at parsing the SVG files manually so that I can create a collection of `SKPath` objects that can be drawn with my own SKPaint.

**Additional context**

I am using this library inside a `SkiaSharp.Views.WPF.SKElement` to draw SVG icons on my UI. I would like to create a `Color` property for the WPF control so that the icons can be recolored at runtime.

**Comment by mattleibow** [comment]
I would suggest having a look at https://github.com/wieslawsoltes/Svg.Skia

That library allows for DOM editing and changes.
