### ISSUE TITLE
Strange rendering of text and tspan when using text-anchor and baseline-shift

### ISSUE THREAD

**Issue by codedevote** [mono/SkiaSharp.Extended#11]
I am currently using SkiaSharp.SVG 1.59.0 and observed some rendering problems with respect to text-anchor and baseline-shift properties.

See the following example svg:
```xml
<?xml version="1.0" standalone="no" ?>
<svg xmlns="http://www.w3.org/2000/svg" fill="white" version="1.1">

    <text x="350" y="50" style="fill: #000000; font-size: 24px; text-anchor: start; ">Normal <tspan style="baseline-shift: -12px;">sub</tspan> NORMAL <tspan style="baseline-shift: 12px;">super</tspan></text>
    
    <text x="350" y="100" style="fill: #000000; font-size: 24px; text-anchor: middle; ">Normal <tspan style="baseline-shift: -12px;">sub</tspan> NORMAL <tspan style="baseline-shift: 12px;">super</tspan></text>
    
    <text x="350" y="150" style="fill: #000000; font-size: 24px; text-anchor: end; ">Normal <tspan style="baseline-shift: -12px;">sub</tspan> NORMAL <tspan style="baseline-shift: 12px;">super</tspan></text>
    
    <line x1="350" x2 =" 350" y1="50" y2="150" stroke="black" stroke-width="1"/>
</svg>
```

When you open this svg in a brrowser (I used Chrome here), you see the following result:

![image](https://user-images.githubusercontent.com/2646473/28825001-dc1a2402-76c4-11e7-8619-5093cad34b48.png)

When you render it using SKSvg class (I used WPF here), you get this result:
![image](https://user-images.githubusercontent.com/2646473/28825075-12832444-76c5-11e7-8c3b-b2e684201508.png)

It seems like the text-anchor attribute is only working as expected, if its value is 'start'. The baseline-shift seems to be ignored completely. 

I had a look in the source code and for me it seems, that SKTextAlignment does not correspond to svg text-anchor positions (as mapped in [ReadTextAlignment](https://github.com/mono/SkiaSharp.Extended/blob/master/SkiaSharp.Extended.Svg/source/SkiaSharp.Extended.Svg.Shared/SKSvg.cs#L976)).
Baseline-Shift seems to be not implemented at all. 

Any idea on how to improve things? I'd be happy to send a PR, as soon as it is clear what to do.

**Comment by codedevote** [comment]
I made some progress on this. What is imho missing from Skia/SkiaSharp in general, is the possibility to output contiguous pieces of formatted text. Take this markdown formatted example:

Normal **and bold** text.

To render this in skia, I need three calls to DrawText and vary the paint / font / typeface and x-coordinate accordingly. Right now, I have implemented my own solution to output formatted text. I integrate the format right into the strings I want to output (like HTML or BBCode) and have a parser that cuts that into pieces and provides a list of SKFormattedText objects that can each be rendered using a single DrawText call (I have an extension method for that). I would be happy to get that code upstream into SkiaSharp, if you are interested. 
With this implementation I can solve the baseline-shift in both directions (ie. IEnumerable<SKFormattedText> <--> outer text + tspans). I am not done with the *text-anchor* yet, but I think it should be possible by measuring the text as it would be rendered using text-anchor="start" and then adjust the x-coordinate. 
What are your thoughts?

**Comment by mattleibow** [comment]
I agree that the area that is lacking is text handling.

SkiaSharp is not designed to handle the rendering of text from some formatted string, but rather gives you all the tools that you may need to DRAW arbitrary text.

We haven't yet had the opportunity to investigate this. But, as demand increases, this will rise up the ranks of the backlog.

**Comment by nvbiryukov** [comment]
As a workaround one can convert text into path and it works ok.

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia

It has an API that is compatible and will just require a namespace change.
