### ISSUE TITLE
[QUESTION] NuGet package for SkiaSharp.Extended.UI 

### ISSUE THREAD

**Issue by rubiomiguel06** [mono/SkiaSharp.Extended#110]
What is the right way to access the SKConfettiView in Xamarin.Forms? I've searched for a nuget package without success, and the nuget SkiaSharp.Extended does not include this view.

Thanks in advance for your help

**Comment by F-Goncalves** [comment]
Hi @rubiomiguel06 ,
did you add the nuget package source 'https://aka.ms/skiasharp-eap/index.json' and activate the checkbox to show prerelease version for nuget packages?

**Comment by mattleibow** [comment]
@rubiomiguel06 have you been able to try out the nugets on the skiasharp-eap feed?

I am working hard to get the APIs stabilized and ready to push a preview to NuGet. I think we have got most of the bugs that we can get now, so a public release is imminent - and yeah, I said that weeks ago.

**Comment by mattleibow** [comment]
The packages are OUT!!! https://www.nuget.org/packages/SkiaSharp.Extended.UI.Maui/2.0.0-preview.59
