### ISSUE TITLE
Add support for textarea

### ISSUE THREAD

**Issue by aloisdeniel** [mono/SkiaSharp.Extended#12]
It would be very usefull to add parsing of [textarea](https://www.w3.org/TR/SVGTiny12/text.html#TextInAnArea).

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     version="1.2" baseProfile="tiny" viewBox="0 0 220 320">

  <title>Basic textflow</title>

  <textArea font-size="25" font-family="Georgia" x="10" y="10" width="200" 
        height="300">Tomorrow, and tomorrow, and
        tomorrow; creeps in this petty pace from day to day, until the last syll&#xAD;able of recorded
        time. And all our yesterdays have lighted fools the way to dusty death.</textArea>
  <rect x="5" y="5" width="210" height="310" stroke-width="3" stroke="#777" fill="none"/>
</svg>
```

![image](https://www.w3.org/TR/SVGTiny12/examples/textArea01.png)

**Comment by aloisdeniel** [comment]
I would love to participate, but I didn't find a proper way to write text in areas with line breaks with SkiaSharp.

It should be doable with `MeasureText` and a dichotomy algorithm but a better way maybe exists.

**Comment by charlesroddie** [comment]
Interested in this topic as I would like in future to render text and maths together.

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia

It has an API that is compatible and will just require a namespace change.
