### ISSUE TITLE
[BUG] Animation fails to load in .NET Maui application

### ISSUE THREAD

**Issue by F-Goncalves** [mono/SkiaSharp.Extended#128]
**Description**

I am trying to run a .NET Maui application with the SKLottieView. But no matter what I try it fails to display the animation and AnimationFailed event is called.

**Code**

See attached solution.

**Expected Behavior**

Lottie animation shows and plays.

**Actual Behavior**

Lottie animation does not show and AnimationFailed is fired.

**Basic Information**

See attached solution.

[LottieMauiSkia.zip](https://github.com/mono/SkiaSharp.Extended/files/9071813/LottieMauiSkia.zip)

**Comment by mattleibow** [comment]
I am wondering if this is the hidden bug in maui GA that did not load TemplatedView. What version of maui are you using? Are you on the latest VS preview?

You can check in the IDE:

<img src="https://user-images.githubusercontent.com/1096616/178855529-b9ad852f-2ba7-4753-8055-d09dbf3bae8a.png" width="300" />

**Comment by mattleibow** [comment]
OK, WOW... So it seems skia can't load the animations when it has a BOM. I saw this when I did a diff between my file and your file and there was no actual difference.

When I opened it in vscode, I noticed this:

| 😢  | 🥲  |
| :-: | :-: |
| ![image](https://user-images.githubusercontent.com/1096616/178857851-22487fd9-81fe-4ebe-972a-7e5b0420b386.png) | ![image](https://user-images.githubusercontent.com/1096616/178858006-9ca59ebb-591a-4a95-a881-e7e8e150fcfc.png) |

I did a save without the BOM and it worked 😢 

I am going to see if I can teach SkiaSharp to load regardless of BOM or see if I can get better errors in SkiaSharp.

**Comment by mattleibow** [comment]
Opened a related bug: https://github.com/mono/SkiaSharp/issues/2166

**Comment by mattleibow** [comment]
A workaround until the build completes is to add the new skottie package directly to your csproj:

```xml
<PackageReference Include="SkiaSharp.Skottie" Version="2.88.1-preview.91" />
```
