### ISSUE TITLE
Add support for clipping

### ISSUE THREAD

**Issue by codedevote** [mono/SkiaSharp.Extended#13]
I discovered there is currently no support for clipping (i.e  *clip-path* attribute and *clipPath* element). I already have a working version that parses the *clipPath* elements from defs - section and applies the clipping to the SKCanvas. By now it is limited to *rect* elements within *clipPath* element, but I should be able to add most of the other primitives pretty fast. 
I would have already sent a PR, but I have some strange issues with the tests. All tests that compare pixels of the resulting bitmap (using SKBitmap.GetPixel method) fail, because GetPixel seems to return random numbers instead of actual color of the pixel. If you want I can send the PR without all tests passing, maybe it's just an issue on my machine (vmware). Please advice how to proceed.

**Comment by mattleibow** [comment]
This will be good to add, thanks.
The issue you may be having is that either you are not clearing the bitmap before drawing the image. I noticed that on some platforms, the memory has arbitrary data. The new bitmap allocates, but does not actually touch the pixels yet.

**Comment by mattleibow** [comment]
Closing this issue as basic support for clipping is now merged in. We should open new issues for specific bugs/features.
