### ISSUE TITLE
[BUG] offset was not present (some svg headers not handled correctly)

### ISSUE THREAD

**Issue by Bxaa** [mono/SkiaSharp.Extended#134]
Exception:
[The given key 'offset' was not present in the dictionary]

Code:
`...New SkiaSharp.Extended.Svg.SKSvg.Load(stream)`...

Version:
Latest 1.60.0 (win10x64)

EXAMPLE: 
File to reproduce https://drive.google.com/file/d/1j9Vi2JtYjXjV6a_R6IjgucbHqBeWPdcw/view?usp=sharing

**Comment by mattleibow** [comment]
SkiaSharp.Extended.Svg has been discontinued in favor of a much more stable and complete Svg.Skia: https://github.com/wieslawsoltes/Svg.Skia
