### ISSUE TITLE
[FEATURE] Support for embedded binary image frames?

### ISSUE THREAD

**Issue by Mephisztoe** [mono/SkiaSharp.Extended#136]
**Is your feature request related to a problem? Please describe.**

I use SVGator for creating animated SVGs. However, .NET MAUI is not (yet) capable of playing animated SVGs.
SVGator recently published an update that allows for the animations to be exported to MP4s.
There are other online services that are able to convert MP4s to lottie-files (json) by extracting the MP4s' frames to images and embedd them as base64 encoded jpges into the json.

However, while the lottie website itself is able to show them, playing them with SkiaSharp.Extended from within a .NET MAUI application seems to be not possible.

**Describe the solution you'd like**

I would like this plugin to be able to play this kind of animation the same way it is able to play regular lottie animations created with Adobe tools.

**Comment by mattleibow** [comment]
SkiaSharp.Extended.Svg has been discontinued in favor of a much more stable and complete Svg.Skia: https://github.com/wieslawsoltes/Svg.Skia
