### ISSUE TITLE
Color in SVG polygon

### ISSUE THREAD

**Issue by CJACQUEL** [mono/SkiaSharp.Extended#14]
Hello, 

I use SKSvg extended. But for an object polygon the style="fill:lime.
But the lime color is not recognized and the polygon is black.
How to specify the fill color with a given value in hexa?
Thx
CJ

**Comment by daniel-luberda** [comment]
It's fixed with this: https://github.com/mono/SkiaSharp.Extended/pull/15

**Comment by CJACQUEL** [comment]
Hello, 
Could you updgrade the nuget SkiaSharp.extended with this problem solved ?
Thx
Cjacquel

**Comment by mattleibow** [comment]
@CJACQUEL This has been merged into master: 4880d05e76fd0d64d1cd5af3fe5956175fb232f2

**Comment by mattleibow** [comment]
Released: https://github.com/mono/SkiaSharp.Extended/releases/tag/v1.59.1-svg
