### ISSUE TITLE
[FEATURE] Could you add AutoRepeat for LottieView

### ISSUE THREAD

**Issue by jingliancui** [mono/SkiaSharp.Extended#151]
I want my lottie image can auto repeat animation because I need this for loading view.
Why not use RepeatCount="2147483647" ?
That's make confused for maintainer.

**Comment by ShadowOfPhantom** [comment]
> I want my lottie image can auto repeat animation because I need this for loading view. Why not use RepeatCount="2147483647" ? That's make confused for maintainer.

Hello! I've put there RepeatCount="-1" and it seems to be working.

**Comment by jingliancui** [comment]
@ShadowOfPhantom Thanks! That's work fine. Hope docs can be written about this.

**Comment by mattleibow** [comment]
I am adding some more docs on this, but don't forget the docs are in markdown here: https://github.com/mono/SkiaSharp.Extended/tree/main/docs

And appear here: https://mono.github.io/SkiaSharp.Extended/api/ui-maui/sklottieview.html

I also accept PRs 😉
