### ISSUE TITLE
ILLink: error IL1011:

### ISSUE THREAD

**Issue by JozefGulaPayius** [mono/SkiaSharp.Extended#154]
Hello, 

I am using the last version of visual studio (17.5.0 Preview 1.0), Net7.0, MAUI (7.0.49) and SkiaSharp.Extended.UI.Maui (2.0.0-preview.59).

My application is working properly in debug mode. However, the build in release mode ends with this error:

`Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm64\linked\SkiaSharp.Views.Android.dll'.
 ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   ....`
   
Do you have some idea how can I fix this problem?

Thank you very much.

**Comment by AswinPG** [comment]
I am also experiencing this issue

**Comment by idenardi** [comment]
I got the same issue here. Any workaround?

**Comment by mattleibow** [comment]
This should be fixed now in the latest versions of SkiaSharp. Can you try the latest previews of Extended?

**Comment by mattleibow** [comment]
Should be fixed.
