### ISSUE TITLE
Bind Lottie Image Source

### ISSUE THREAD

**Issue by pvoelker** [mono/SkiaSharp.Extended#160]
I'm writing a game where I want to show a random Lottie image when a child gets a question right.

I'm trying to do something like this to auto trigger the animation when the 'source' is set (in this example via 'LottieImage'.

The AnimationLoaded never seems to trigger.  Am I approaching this wrong?

```
            <skia:SKLottieView
                  IsVisible="{Binding Path=LottieImage, Converter={StaticResource TextNotNullOrEmptyToBool}}"
                  Source="{Binding Path=LottieImage}"
                  RepeatCount="-1"
                  HorizontalOptions="Fill"
                  VerticalOptions="Fill">
            </skia:SKLottieView>
```

```
    public class AnimationOnLoad : Behavior<SKLottieView>
    {
        protected override void OnAttachedTo(SKLottieView control)
        {
            control.AnimationLoaded += Control_AnimationLoaded;
            base.OnAttachedTo(control);
        }

        protected override void OnDetachingFrom(SKLottieView control)
        {
            control.AnimationLoaded -= Control_AnimationLoaded;
            base.OnDetachingFrom(control);
        }

        private void Control_AnimationLoaded(object sender, EventArgs e)
        {
            var control = sender as SKLottieView;

            if (control != null)
            {
                control.IsAnimationEnabled = true;
            }
        }
    }
```

**Comment by pvoelker** [comment]
OK, I figured out the problem.  I was trying to bind against a 'string'.   I need to bind against SKLottieImageSource.  Which required the use of SKLottieImageSourceConverter.ConvertFromString

**Comment by pvoelker** [comment]
Maybe this will help.  Here is the code I have...

_XAML Snippet_
`<skia:SKLottieView IsVisible="{Binding Path=LottieImage, Converter={StaticResource ObjectNotNullToBool}}" Source="{Binding Path=LottieImage}" RepeatCount="1" HorizontalOptions="Fill" VerticalOptions="Fill" IsComplete="{Binding Path=IsAnimationComplete}"> </skia:SKLottieView>`

_View-Model Snippets_
`private SKLottieImageSourceConverter _lottieConverter = new SKLottieImageSourceConverter();`

`private SKLottieImageSource _lottieImage = null;`
`public SKLottieImageSource LottieImage`
`{`
`    get => _lottieImage;`
`    set => SetProperty(ref _lottieImage, value);`
`}`

`LottieImage = (SKLottieImageSource)_lottieConverter.ConvertFromString(_name-of-raw-resource_);`

**Comment by Strypper** [comment]
```
Source="{x:Binding ComponentData.LottieUrl,
                               Source={x:Reference root},
                               Mode=OneWay,
                               Converter={x:StaticResource SKLottieImageSourceConverter}}"
```
Here is my version The `ComponentData.LottieUrl` is `string` type and actual value is `dotnetbot.json`

**Comment by pvoelker** [comment]
Is anything showing up in the debug output?  If there is a straight up binding error, a message will appear there...

**Comment by Strypper** [comment]
Oh it does 
`Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'dotnetbot.json' cannot be converted to type 'SkiaSharp.Extended.UI.Controls.SKLottieImageSource'`

**Comment by Strypper** [comment]
The converter is failing? or is the way I used it wrong?` dotnetbot.json `set directly in xaml work

**Comment by pvoelker** [comment]
Do you have the JSON lottie file under the 'raw resource' directory?  Example:  MyApp/Resources/Raw/happy-dance.json

**Comment by Strypper** [comment]
> Do you have the JSON lottie file under the 'raw resource' directory? Example: MyApp/Resources/Raw/happy-dance.json

Yes I put it in there all the time

**Comment by Strypper** [comment]
I think this is `converter `issue or maybe `SKLottieImageSource `since VS keep scream can't find `FromFile `method 
![image](https://user-images.githubusercontent.com/32596308/218193570-60ef6b16-3eaa-4c41-8ea0-7be0b2c6522d.png)

**Comment by Diogoepronto** [comment]
> OK, I figured out the problem. I was trying to bind against a 'string'. I need to bind against SKLottieImageSource. Which required the use of SKLottieImageSourceConverter.ConvertFromString

I've had a similar problem and that solution worked perfectly, thanks!
