### ISSUE TITLE
FinishedAnimation equivalent for Lottie animations

### ISSUE THREAD

**Issue by pm64** [mono/SkiaSharp.Extended#161]
I believe many people porting their Xamarin.Forms projects to MAUI are coming to SkiaSharp.Extended from Lottie.Forms, in order to use SKLottieView as a replacement for AnimationView.

In Lottie.Forms, AnimationView had an OnFinishedAnimation event. A typical use case would be displaying a popup to show an animation, then closing the popup automatically when the animation finishes.

SkiaSharp.Extended doesn't appear to expose an equivalent event. What is the recommended way to satisfy the above use case?

**Comment by haavamoa** [comment]
I was also in the need of knowing when the animation finished to provide the best UX when the animation was showing and finished. I found a workaround:

You can subscribe `PropertyChanged` event and listen for the `IsCompleted` property changing. This will be come `true` when it's finished.

**Comment by mattleibow** [comment]
I could add an event, but I just want to check what would be the expected for a looping animation.

For a normal, no loop I would assume it runs once and then fires. For a loop X times, I assume it will loop X times and then fire at the end.

So in this thought, a looping will never fire as it never finishes?

**Comment by pm64** [comment]
@mattleibow I think the expectation would be for the event to never fire in the infinite-loop scenario.

But your question makes me realize the idea can be improved, by splitting this into two events: `OnFinishedLoop` and `OnFinishedPlayback`.

`OnFinishedLoop` would fire on completion of each loop, and `OnFinishedPlayback` would fire on completion of the final loop (if any).

**Comment by mattleibow** [comment]
Sounds like a new feature request!!! :)
