### ISSUE TITLE
[BUG] SkiaSharpDemo: trophy.json file missing

### ISSUE THREAD

**Issue by softlion** [mono/SkiaSharp.Extended#162]
**Description**

SkiaSharpDemo should display a trophy lottie file. But does not.

The file is completely missing from this maui demo app.

Also, adding a file N times (to the N platform folders) is not ideal. Using an embedded resource loader instead in the SKLottieImageSourceConverter would fix this nonsense.

**Comment by mattleibow** [comment]
It should be there once: https://github.com/mono/SkiaSharp.Extended/blob/1f302f3ae190cbbfe7f5c3205cb8b8c1b1286415/samples/Maui/SkiaSharpDemo/Resources/Raw/Lottie/trophy.json

I just tested now and it does.

**Comment by mattleibow** [comment]
Closing this issue as it appears to be working. Please file a new issue with an error message or a screenshot if this is still happening.
