### ISSUE TITLE
[FEATURE] SKLottieImageSource fromFile method is internal

### ISSUE THREAD

**Issue by IeuanWalker** [mono/SkiaSharp.Extended#170]
`SKLottieImageSource` fromFile method is internal. Meaning you cant set the source from C# code

**Comment by thomaskaelin** [comment]
I noticed this issue was well while porting an existing Xamarin.Forms-app to .NET MAUI.

@IeuanWalker Did you find any workarounds for this?

**Comment by IeuanWalker** [comment]
@thomaskaelin no sorry, havnt worked on it since i found this issues

**Comment by JaHdz** [comment]
I've set the property like this:

```
BackgroundLottie.Source = new SKFileLottieImageSource
                {
                    File = "confetti_animation.json"
                };
```

**Comment by thomaskaelin** [comment]
@JaHdz Thanks a lot for the tip. I wasn't aware of `SKFileLottieImageSource`. I will give it a try. 👍

**Comment by mattleibow** [comment]
Thanks. At the time I was unsure, so I made it all internal. I have a PR to clean this up.
