### ISSUE TITLE
[QUESTION] Is this library still supported? Lottie just does not display in iOS

### ISSUE THREAD

**Issue by TedMobile** [mono/SkiaSharp.Extended#173]
Hi,
As ever I am very grateful to any person who gives up their free time to give back to the community. 

I would really like to start using lottie in my Maui app but it just does not display in iOS let alone popups etc.. 

Is this library still supported?  Does anyone have a sample that work in iOS? 

Is there an alternative to this library?

many thanks

**Comment by techscx** [comment]
I can confirm, that lottie does not render - without any exception to be thrown - in IOS using Visual Studio Windows as build host and debugging on a local IOS device connected to the Windows computer (IOS local device & hot reload).

But:
Lottie renders on IOS, when using a Mac as build host. This can be done either by using Visual Studio Windows -> IOS Simulator or IOS Remote Device or compiling and debugging directly on Visual Studio Mac.

**Comment by developer9969** [comment]
I can confirm too that lottie does not work on windows host!

And does not work in iOS using mac either if you using a service provider to hook a viewmodel - page

https://github.com/mono/SkiaSharp.Extended/issues/147

I will test on popups but dont think it works there either..  

This seems to have been a known bug for months , and the main coder of this library he is probably too busy firefighting Maui bigger issues...

**Comment by mattleibow** [comment]
Try updating skiasharp and skiasharp.views to the latest preview.

There may have been some issues with the new Apple chips. But if this is classic xamarin then I am not sure.

If you have a sample app lying around then it will help with testing.

**Comment by TedMobile** [comment]
@mattleibow  
I will try to update and see if makes a difference you can easily replicate the issue if you use any of the above and you use a windows machine running iOS device phisical

1. https://github.com/jfversluis/MauiLottieAnimationsSample  
2. https://github.com/mono/SkiaSharp.Extended/issues/147  (raised by pureween) 
3. Add  a popup and put a lottie there and run again in windows against a ios phone

Would be nice if we can finally use lottie in maui in both iOS and android!

thanks

**Comment by TedMobile** [comment]
@mattleibow  hi - wondering if you had any change to look at why lottie does not work in the mentioned scenarios, 
Any updates on this nuget soon?

many thanks

**Comment by mattleibow** [comment]
I have had a chance to look. I fixed the one and the other is an issue in the MCT that I believe they have fixed: https://github.com/CommunityToolkit/Maui/pull/1342. I see this issue is more of a duplication of other issues, so I will close this. 

With regards to support, this library is not 100% an official, supported product and is more like cool things the skiasharp team does and will release. Think community toolkit, but for skia. Maybe at some point I will see about merging this under the community toolkit org before 2.x goes stable.
