### ISSUE TITLE
[BUG] Animation not playing when inherit from SKLottieView

### ISSUE THREAD

**Issue by naaeef** [mono/SkiaSharp.Extended#177]
**Description**

If I inherit from SKLottieView and use this class for showing an animation, the animation is not running / visible. We want to use inheritance to make some customization.

**Code**

I'm using inheritance like this. If I use CustomSKLottieView, it does not show the animation (see reproduction sample).
```

public class CustomSKLottieView : SKLottieView
    {
        
    }

```

**Expected Behavior**
Animations also work when using inheritance.

**Actual Behavior**

Animation are not working when using inheritance.

**Basic Information**

- Version with issue:  2.0.0-preview.61
- IDE:  Rider
- Platform: Android and iOS
- Target Devices:  iOS simulator / Android emulator
  
**Screenshots**

![image](https://github.com/mono/SkiaSharp.Extended/assets/43339071/7c909f7a-60b7-41a3-9a90-2971810d5235)
(App should show the animation twice, at the top SKLottieView is used, at the bottom a inherited class is used)

**Reproduction Link**
[LottieReproduction.zip](https://github.com/mono/SkiaSharp.Extended/files/12342834/LottieReproduction.zip)

**Comment by PavloLukianets** [comment]
@mattleibow we have the same problem, would be nice to take a look

**Comment by PavloLukianets** [comment]
Workaround: add ApplyToDerivedTypes = true here: https://github.com/mono/SkiaSharp.Extended/blob/main/source/SkiaSharp.Extended.UI.Maui/Controls/Lottie/SKLottieViewResources.shared.xaml
