### ISSUE TITLE
SVG Rendering Issue

### ISSUE THREAD

**Issue by RichiCoder1** [mono/SkiaSharp.Extended#23]
I'm attempting to replace our SVG rendering w/ skia sharp's and I ran into an issue.

Source SVG: https://cdn.rawgit.com/chocolatey/chocolatey-coreteampackages/edba4a5849ff756e767cba86641bea97ff5721fe/icons/chrome.svg

Expected Render: 
<img width="193" alt="chrome_corrnt" src="https://user-images.githubusercontent.com/2391878/31511196-91a24452-af4c-11e7-9b54-3d1f5f559710.PNG">

Actual Render:
<img width="200" alt="chrome_incorrect" src="https://user-images.githubusercontent.com/2391878/31511225-b1809ad0-af4c-11e7-914e-5cae0b583d36.PNG">

It looks like there

Rendering Code:
```c#
                using (var stream = imageStream.OpenRead())
                {
                    var svg = new SKSvg(new SKSize());
                    svg.Load(stream);

                    var canvasMin = Math.Min(e.Info.Width, e.Info.Height);
                    var svgMax = Math.Max(svg.Picture.CullRect.Width, svg.Picture.CullRect.Height);
                    var scale = canvasMin / svgMax;
                    var matrix = SKMatrix.MakeScale(scale, scale);

                    e.Surface.Canvas.Clear(SKColor.Empty);
                    e.Surface.Canvas.DrawPicture(svg.Picture, ref matrix);
                    return;
                }
```

Where `e.Surface` is the rendering surface of a WPF SKElement.

It looks like `<circle cx="50%" cy="50%" r="41" fill="url(#a)" />`  isn't getting relatively positioned properly.

**Comment by RichiCoder1** [comment]
Ahh, looks like ya'll assume absolutely positioned elements.

**Comment by mattleibow** [comment]
At the current time, the SVG bits do not support relative positioning.

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.
