### ISSUE TITLE
[QUESTION] When can we expect a stable release of SkiaSharp.Extended (rather than using a preview version)?

### ISSUE THREAD

**Issue by ChristopherStephan** [mono/SkiaSharp.Extended#249]
SkiaSharp.Extended is still a preview version but we want to use it in our project as a reference. Currently we need to disable the following warning, that our library release should not have a prerelease dependency. When can we expect a stable release of this package?

> A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "NuGet.Versioning [4.7.0-preview4.5065, )" or update the version field in the nuspec.

https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5104

**Comment by mattleibow** [comment]
Hello folks. I think it is time. Just fixing a memory leak and then will probably start the release process.

**Comment by mattleibow** [comment]
I just pushed what I think is the last preview of this: https://www.nuget.org/packages/SkiaSharp.Extended.UI.Maui/2.0.0-preview.94

A changelog is here: https://github.com/mono/SkiaSharp.Extended/releases/tag/v2.0.0-preview.94

I am hoping to push a bunch of SkiaSharp releases later this week, and this library will finally get its debut as a stable package after many releases.
