### ISSUE TITLE
SVG doesn't work with css styling

### ISSUE THREAD

**Issue by Craig-TSS** [mono/SkiaSharp.Extended#25]
I have some pretty basic SVGs that have their colors assigned in a style, but these will not render in SkiaSharp.

In the svg it has
`<style>.cls-1{fill:#f9f9f9;}.cls-2{fill:#0066b2;}.cls-3{fill:#f9a533;}</style>`
and when defining a path, those styles are referenced, eg
`<path class="cls-3" d="M39.91,40.14,37.84,29.56a2.61,2.61,0,0,0-2.9-2.12H25.28l-.11.4a23.73,23.73,0,0,1,9.09,4.56A18.39,18.39,0,0,1,39.91,40.14Z"/>
`
But from what i can tell any SVG using styles (class) does not render correctly. All i get it everything in black. 

Attached is a simple visa card logo in SVG which doesn't wok with SkiaSharp.
[visa1.zip](https://github.com/mono/SkiaSharp.Extended/files/1448832/visa1.zip)

**Comment by daniel-luberda** [comment]
https://github.com/mono/SkiaSharp.Extended/pull/24 - it's implemented here

**Comment by daniel-luberda** [comment]
It's now here:  https://github.com/mono/SkiaSharp.Extended/pull/75

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.
