### ISSUE TITLE
fill-rule is not being applied correctly.

### ISSUE THREAD

**Issue by justinjedlicka** [mono/SkiaSharp.Extended#26]
The fill-rule property is not being applied correctly.

[http://www.w3.org/TR/SVG2/painting.html#FillRuleProperty](http://www.w3.org/TR/SVG2/painting.html#FillRuleProperty)

There are two example svg files provided by w3.

**fillrule = evenodd**
![fill-rule evenodd svg](https://www.w3.org/TR/SVG2/images/painting/fillrule-evenodd.svg)
Source: [https://www.w3.org/TR/SVG2/images/painting/fillrule-evenodd.svg](https://www.w3.org/TR/SVG2/images/painting/fillrule-evenodd.svg)

**fillrule = nonzero**
![fill-rule nonzero svg](https://www.w3.org/TR/SVG2/images/painting/fillrule-nonzero.svg)
Source: [https://www.w3.org/TR/SVG2/images/painting/fillrule-nonzero.svg](https://www.w3.org/TR/SVG2/images/painting/fillrule-nonzero.svg)

They should look like:

**fillrule = evenodd**
![fill-rule evenodd png](https://www.w3.org/TR/SVG2/images/painting/fillrule-evenodd.png)
Source: [https://www.w3.org/TR/SVG2/images/painting/fillrule-evenodd.png](https://www.w3.org/TR/SVG2/images/painting/fillrule-evenodd.png)

**fillrule = nonzero**
![fill-rule nonzero png](https://www.w3.org/TR/SVG2/images/painting/fillrule-nonzero.png)
Source: [https://www.w3.org/TR/SVG2/images/painting/fillrule-nonzero.png](https://www.w3.org/TR/SVG2/images/painting/fillrule-nonzero.png)

When they are loaded using SKSvg.Load they are both using a Winding FillType and look like "fill-rule = nonzero"

```
var svg = new SKSvg();
svg.Load(fillruleImage);
canvas.DrawPicture(svg.Picture);
```

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.
