### ISSUE TITLE
Default stroke-width scales incorrectly.

### ISSUE THREAD

**Issue by iansteed** [mono/SkiaSharp.Extended#27]
The line's stroke-width does not scale correctly when not specified. See example below. The SVG specification indicates stroke-width should default to a value of 1. Setting the stroke-width="1"
attribute appears to be working correctly.

**SVG**
`<svg viewBox="0 0 20 20">`
`<line x1="0" y1="0" x2="20" y2="20" stroke="#000000" />`
`<line x1="20" y1="0" x2="0" y2="20" stroke="#000000" />`
`</svg>`

**Expected Results**
_20 x 20_
![expected-20](https://user-images.githubusercontent.com/10568040/34580642-8c1dc4ba-f142-11e7-978d-d900800a77ac.png)
_100 x 100_
![expected-100](https://user-images.githubusercontent.com/10568040/34580650-902403f8-f142-11e7-9e4b-eb3892618dce.png)

Rendered with W3 and Chrome
(https://www.w3schools.com/graphics/tryit.asp?filename=trysvg_stroke0)

**Actual Results**
_20 x 20_
![actual-20](https://user-images.githubusercontent.com/10568040/34580652-944d29be-f142-11e7-9699-4409fbdd9e63.png)
_100 x 100_
![actual-100](https://user-images.githubusercontent.com/10568040/34580659-98554f00-f142-11e7-8432-cb2ca9eb9898.png)

Rendered with the following code:
`public static SKImage ToSKImage(this SkiaSharp.Extended.Svg.SKSvg svg, SKSizeI size)`
`{`
`var scaleX = size.Width / svg.CanvasSize.Width;`
`var scaleY = size.Height / svg.CanvasSize.Height;`
`var transform = SKMatrix.MakeScale(scaleX, scaleY);`
`return SKImage.FromPicture(svg.Picture, size, transform);`
`}`

**Comment by maruhe** [comment]
hi there I may have a similar problem on loading svg files
expected result visualised by SVG-Viewer app:
![SVG Viewer_Screenshot_2020 02 27_16 12 58](https://user-images.githubusercontent.com/49123648/75457142-63004400-597c-11ea-8a3e-4f037f868661.jpg)

result in my app and also XamaRed.Forms.Svg.Samples which I used to test cause it uses SkiaSharp:
![XamaRed Forms Svg Samples_Screenshot_2020 02 27_16 13 19](https://user-images.githubusercontent.com/49123648/75457453-c5594480-597c-11ea-9f4d-87ecaef87fe4.jpg)


other svg-files work correct, if helpful I can upload a sample file

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.

**Comment by KrystofS** [comment]
Even though this library is deprecated and might not provide as complete implementation of the SVG standard as Svg.Skia does. I´d like to point out that it is still significantly faster.
![image](https://user-images.githubusercontent.com/53654296/152636784-fe5e17e5-f720-4cae-bd26-7343339c4f2a.png)
```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using SkiaSharp;
using Svg;
using System.Text;

namespace Benchmark01
{
    [Orderer(BenchmarkDotNet.Order.SummaryOrderPolicy.FastestToSlowest)]
    [SimpleJob(RuntimeMoniker.Net48)]
    [SimpleJob(RuntimeMoniker.Net60)]
    public class SkiaSvgBenchmark
    {
        private SKPicture pict;
        private Stream xmlStream;
        private readonly SkiaSharp.Extended.Svg.SKSvg skiaSharp = new SkiaSharp.Extended.Svg.SKSvg();
        private readonly Svg.Skia.SKSvg svgSkia = new Svg.Skia.SKSvg();

        [Params(10)]
        public int Size { get; set; }

        [IterationSetup]
        public void Setup()
        {
            SvgDocument svgDoc = SvgDocument.Open(@"path to my test file");
            var xml = svgDoc.GetXML();
            xmlStream = new MemoryStream(Encoding.UTF8.GetBytes(xml));
        }

        [IterationCleanup]
        public void Cleanup()
        {
            xmlStream.Dispose();
            pict.Dispose();
        }

        [Benchmark]
        public void Skiasharp()
        {
            pict = skiaSharp.Load(xmlStream);
        }

        [Benchmark]
        public void SvgSkia()
        {
            pict = svgSkia.Load(xmlStream);
        }
    }
}
```
