### ISSUE TITLE
Porting SkTextBox to support draw text in wrap

### ISSUE THREAD

**Issue by mattleibow** [mono/SkiaSharp.Extended#28]
_From @tangkhaiphuong on June 9, 2017 7:48_

Skia native version have SkTextBox support draw text in wrap, please implement to support this feature.

https://github.com/google/skia/blob/fcee51038aeaf3596a4ffcdba0bf18e3155e09b9/include/utils/SkTextBox.h

_Copied from original issue: mono/SkiaSharp#313_

**Comment by mattleibow** [comment]
This may be related to, or a precursor to: https://github.com/mono/SkiaSharp.Extended/issues/11

**Comment by mattleibow** [comment]
This may be related to, or a precursor to: https://github.com/mono/SkiaSharp.Extended/issues/12

**Comment by mattleibow** [comment]
_From @gdchet on September 27, 2017 14:18_

This is desperately needed. Trying to measure text size with Harfbuzz and get the right line breaks from ICU to create wrapped text. It's getting over complicated and the end result is not pretty!

**Comment by nornagon** [comment]
It might be worth considering how to support inline text style changes, **like this** or [like this](), which could potentially affect the width of the text. SkTextBox doesn't support those, as far as I can tell.

**Comment by mdonogma** [comment]
Is this available yet? Need it asap

**Comment by ryancheung** [comment]
bump

**Comment by ryancheung** [comment]
where is the `SkTextBox.h` now?

**Comment by ryancheung** [comment]
It seems to be deleted.

**Comment by ryancheung** [comment]
Then I found it was replaced by https://github.com/google/skia/blob/master/modules/skshaper/include/SkShaper.h

**Comment by ryancheung** [comment]
https://github.com/google/skia/blob/master/modules/skparagraph/include/Paragraph.h
The Paragraph module should be what we want.

**Comment by artemious7** [comment]
bump

**Comment by ryancheung** [comment]
https://github.com/ryancheung/SkiaTextRenderer
I just made it.

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.
