### ISSUE TITLE
[BUG] Fails to load the animation after the resource dictionary is switched

### ISSUE THREAD

**Issue by kycuff** [mono/SkiaSharp.Extended#284]
**Description**

After switching theme with .Net Maui causes the animation to no longer work but after an app restart it works.

Where the lottie animation should render there is just a blank space but there are no errors or no crashes.

IOS appears to be ok and it is just Android with the issue.

**Code**
All the code does is switch out the ResourceDictionary that is used.
```csharp
Application.Current!.Resources = themeSwitch.IsToggled ? new DarkTheme() : new LightTheme();
```

**Expected Behavior**

Would still expect the lottie animation to play after changing the theme.

**Actual Behavior**

Where the lottie animation should render there is just a blank space but there are no errors or no crashes.

**Basic Information**

- Version with issue:  2.0.0
- Last known good version:  unknown
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - Android: 13
  - iOS:  17.5
- Target Devices:   
  - Device Samsung Galaxy S20
  - Device iPhone 11 Pro
  

**Reproduction Link**

https://github.com/kycuff/LottieIssueApp

**Comment by IeuanWalker** [comment]
Also experiencing this
