### ISSUE TITLE
Rendering of <tspan> element not working...

### ISSUE THREAD

**Issue by educos35** [mono/SkiaSharp.Extended#29]
Hi,
I just tested a SVG produced by SVGMaker from a Microstation file. The file has produced the piece of following SVG...
<text font-family="Arial" font-size="46" fill="#000000" font-weight="700" font-style="italic">
<tspan x="7212,7243,7268,7296,7321,7339,7364" y="3561">Repère </tspan>
...
</text>
The <tspan> element is conform to SVG spécification, but the format of x coordinate is not taken into account in SkiaSharp SVG and is set to 0 (normal as far I saw in the source code). So all the texts defined are put at the left side of the SVG drawing....

I have a temporary solution as I can force SVGMaker to draw text whether to use text, but I think it would be good to add implementation of the specification for text/tspan in the library.

Regards.

Eric.

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.
