### ISSUE TITLE
[Question] Using the build targets for custom typeface

### ISSUE THREAD

**Issue by sylvain-toptal** [mono/SkiaSharp.Extended#32]
Is it possible to use your IconifyGenerator for custom typeface fonts?  It doesn't appear to be included in the Nuget yet it would be a massive timesaver.  I think Refit do that as it is required for their code generation process, a situation that is similar to what you are doing here.

Admitedly, this is probably an advanced scenario which would require documenting unless you add an `Attribute` to tag custom fonts classes and their matching data for parsing.

Thanks

**Comment by adamhill** [comment]
Me too. Our Web team & designer uses IcoMoon with CSS templates and we would like to use their mappings and custom font in our Xamarin project.

**Comment by sylvain-toptal** [comment]
You can most likely directly import the .target and the IconifyGenerator class and change your .csproj to use the generator.  Check what they did in the icon projects.

This ticket is more about making this easier, it seems possible to use the generator by manually editing the project file.

**Comment by mattleibow** [comment]
I will investigate this and see if I can release it.

**Comment by brianjtools** [comment]
I was able to include my custom icon font in the demo.  
1) Downloaded and built the Solution.
2) The  IconifyGenerator is a command line app and so used it to create the template for my font by pointing it to my font file and requesting the option to create the template file.
3) Copied one of the font templates, deleted the bin and obj folders in the copy and renamed it for my font and edited the template for my font name.  I also included my font in the folder and edited .csproj to point to my font for the RemoteFontFile.  Deleted the RemoteStyleSheet line as with the template the generator created it doesn't seem to be needed.
4) Built that and then also included the font project as a ProjectReference in the demo .csproj
5) Added a line to the demo to use my font with it's own special codepoints.
6) Built and ran perfectly.  Now I have the font to use in my own projects.

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.
