### ISSUE TITLE
Release NuGet package 1.59.2 with fixes

### ISSUE THREAD

**Issue by vividos** [mono/SkiaSharp.Extended#33]
I'm using SkiaSharp.Extended.Svg to load and render SVG images. I stumbled upon the error "For security reasons DTD is prohibited in this XML document", which was already fixed by pull request #17. Can we have an updated NuGet package (there is already a milestoe 1.59.2 with no open issues)? Thank you!

**Comment by mattleibow** [comment]
Let me release this...

**Comment by vividos** [comment]
Thank you!
