### ISSUE TITLE
Draw Svgs with provided paints color

### ISSUE THREAD

**Issue by joreg** [mono/SkiaSharp.Extended#37]
helo,

i was hoping to be able to draw svgs with a paints color that i provide with the DrawPicture() call, ie. overriding the style set in the file. i'd like to load little icons as svgs and draw them in different colors on demand but it seems the drawing always takes the style saved in the file and only falls back to black when i remove the style from the file.

or am i missing something?

**Comment by ryanholden8** [comment]
Hey @joreg, this is working for me:

```csharp
using (Stream stream = ResourceAssembly.GetManifestResourceStream(fullResouceId))
{
    SKSvg svg = new SKSvg();
    svg.Load(stream);

    SKImageInfo info = args.Info;
    canvas.Translate(info.Width / 2f, info.Height / 2f);

    SKRect bounds = svg.ViewBox;
    float xRatio = info.Width / bounds.Width;
    float yRatio = info.Height / bounds.Height;

    float ratio = Math.Min(xRatio, yRatio);

    canvas.Scale(ratio);
    canvas.Translate(-bounds.MidX, -bounds.MidY);

    // Default Color is equivalent to null
    if (!Color.IsDefault)
    {
        using (var paint = new SKPaint())
        {
            paint.ColorFilter = SKColorFilter.CreateBlendMode(Color.ToSKColor(), SKBlendMode.SrcIn);
            canvas.DrawPicture(svg.Picture, paint);
        }
    }
    else
    {
        canvas.DrawPicture(svg.Picture);
    }
}
```

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.
