### ISSUE TITLE
SKCanvasView Touch Location from SKTouchEventArgs is not found inside SKPath(created using CreatePiePath())

### ISSUE THREAD

**Issue by azeemchaudhrry** [mono/SkiaSharp.Extended#46]
I am using the SKCanvasView in view.
using SkiaSharp.Extended the pie paths are created.
Enable Touch on SKCanvasView but on inside touch event arg the location is not found inside the path?

**Comment by mattleibow** [comment]
I am not sure what youe mean here?
 >  the location is not found inside the path

The touch locations are based on the location in the entire canvas.

**Comment by azeemchaudhrry** [comment]
I did not find the reason behind the issue.
Actually I was using `SkiaSharp.Extended.SKGeometry` to draw a piechart.
when user selected one of the parts, that location is not found inside any path.
`path.contains(x,y)`
I am not using `SkiaSharp.Extended.SKGeometry` anymore to draw a piechart.
