### ISSUE TITLE
Unable to center icons within a view (possible error with measure/draw text?)

### ISSUE THREAD

**Issue by pfaucon** [mono/SkiaSharp.Extended#47]
I'm trying to create a view which will allow me to put a single glyph, centered, on the screen.  My goal then is to determine where I should tell SkiaSharp to begin drawing the glyph, which has consumed significantly more time than I had expected.  It is entirely possible that I misunderstand how SkiaSharp is working, but I suspect that there is something wrong with the values being provided.  Below is my OnPaintSurface, and the project itself is attached below.

The 2 phenomenon that make me believe it is a problem with SkiaSharp itself are:

1) inconsistent math: In the image below (the code is below) I draw a circle at the center of the view. I draw a box representing the width and height of the measured text, and then I draw the text.  My math seems correct for making the box offsets, but the text doesn't even hit the box at all, seeming to be inconsistently attached to it.  My understanding of the input parameters seems to suggest that at the very least the icon should begin drawing at the bottom-left corner of the rectangle, but I seem to drastically misunderstand something.
![image](https://user-images.githubusercontent.com/3473919/43509934-5b59896e-9574-11e8-909d-2e9b13b01de7.png)

2) Failed lookups: On the right side there is a globe icon with no box, this is because {{fa-globe}} seems to have no bounding box (the SKTextRunLookup comes up with a 0 bounding box both for the pre-icon and the icon itself). It is worth noting that when I remove "TextEncoding = SKTextEncoding.GlyphId" the globe gets a bounding box, and all the bounding boxes change, but they are all still wrong.

I then have 2 questions:
1) is there something dumb that I am doing here?
2) is there a way that I can "drawtext" specifying the center instead of the start position?

    public class SKIconLabel : SKCanvasView
    {

        protected override void OnPaintSurface(SKPaintSurfaceEventArgs e)
        {
            base.OnPaintSurface(e);

            var w = e.Info.Width;
            var h = e.Info.Height;
            var midX = e.Info.Rect.MidX;
            var midY = e.Info.Rect.MidY;
            var canvas = e.Surface.Canvas;
            canvas.Clear();

            var ScaledTextSize = Math.Min(w, h) * (float).4;

            SKPaint outlinePaint = new SKPaint
            {
                IsStroke = true,
                Color = SKColors.Red
            };

            SKPaint iconPaint = new SKPaint
            {
                TextSize = ScaledTextSize,
                IsAntialias = true,
                TextEncoding = SKTextEncoding.GlyphId
            };

            float textWidth = 0;
            float textHeight = 0;
            var runs = SKTextRun.Create(Icon, SKTextRunLookup.Instance);

            var hasBounds = false;
            foreach (var rn in runs)
            {
                var bounds = new SKRect();
                var sz = iconPaint.MeasureText(rn.Text, ref bounds);

                textWidth += bounds.Width;
                textHeight += bounds.Height;

                if (bounds.Height > 0)
                {
                    canvas.DrawRect(midX - textWidth/2, midY - textHeight/2, textWidth, textHeight, outlinePaint);
                    hasBounds = true;
                }
            }
            if (!hasBounds)
            {
                Debug.WriteLine($"Failed to find bounds for {this.Icon}");
            }

            canvas.DrawIconifiedText(Icon, midX - textWidth/2, midY - textHeight/2, iconPaint);

            outlinePaint.IsStroke = false;
            canvas.DrawCircle(midX, midY, 5, outlinePaint);
        }

        public static BindableProperty IconProperty =
            BindableProperty.Create(nameof(Icon), typeof(string), typeof(SKIconLabel), "{{fa-plus color=000000}}",
                BindingMode.OneWay, null, (bindable, oldValue, newValue) =>
                {
                    var ctrl = (SKIconLabel)bindable;
                    ctrl.Icon = (string)newValue;
                });
        public string Icon
        {
            get { return (string)GetValue(IconProperty); }
            set
            {
                if (value == null) return;

                SetValue(IconProperty, value);
                InvalidateSurface();
            }
        }
    }

Attached project, relevant sources are Controls/SKIconLabel and AboutPage.xaml
[IconTest.zip](https://github.com/mono/SkiaSharp.Extended/files/2248635/IconTest.zip)

**Comment by pfaucon** [comment]
I have it improved (not fixed), but in a way that I am thoroughly convinced is wrong.  The changes I made were:

1) the y direction with respect to painting is inverted with respect to text (e.g. - moves down for drawRect, but up for drawText)

2) the "height" returned is the height to be drawn, the "width" returned is 1/2 of the true width of the view on Android, but is close to the true width on iOS (not exact, but inconsistently close).  

Is this an expected behavior noted somewhere that I have missed? Or is it just a fluke that it happened to work out with these numbers and isn't the true behavior?

Screenshots with code :
```
             foreach (var rn in runs)
              {
                var bounds = new SKRect();
                var sz = iconPaint.MeasureText(rn.Text, ref bounds);

                textWidth += bounds.Width;
                textHeight += bounds.Height;

                if (bounds.Height > 0)
                {
                    canvas.DrawRect(midX - textWidth/2, midY - textHeight/2, textWidth, textHeight, outlinePaint);
                    canvas.DrawIconifiedText(Icon, midX - textWidth / 2 , midY + textHeight / 2, iconPaint);
                    hasBounds = true;
                }
            }
```

Android:
![image](https://user-images.githubusercontent.com/3473919/43511528-e792020e-9578-11e8-9b38-8cd06b4c50a8.png)


iOS:
![image](https://user-images.githubusercontent.com/3473919/43511549-f6cc5012-9578-11e8-9ee3-7b51ef2e9a26.png)

**Comment by pfaucon** [comment]
I found the TextAlign option, which I was temporarily very excited about, it seems to correct the x centering, but fails with the y.  

            SKPaint iconPaint = new SKPaint
            {
                TextSize = ScaledTextSize,
                IsAntialias = true,
                TextAlign = SKTextAlign.Center, // added
            };

            ...

            canvas.DrawIconifiedText(Icon, midX, midY, iconPaint);

![image](https://user-images.githubusercontent.com/3473919/43630421-951374fc-9700-11e8-9be0-731485784863.png)

If I hybridize the solution, using text centering and adding half the height of the bounding box, it seems to work reasonably well.  It's not right, and it is . a terrible way of arriving at the solution, but visually close enough.  If you have some feedback on what I might be doing wrong I would really appreciate it.  I suspect there is some weirdness in the scaling (retina vs non), but I am not particularly good with graphics so I'm not sure if I can get much deeper.

            var runs = SKTextRun.Create(Icon, SKTextRunLookup.Instance);

            float yHeight = 0;
            foreach (var rn in runs)
            {
                var bounds = new SKRect();
                var sz = iconPaint.MeasureText(rn.Text, ref bounds);
                if (bounds.Height > 0)
                {
                    yHeight += bounds.Height;
                    bounds.Left += midX;
                    bounds.Right += midX;
                    bounds.Top += midY;
                    bounds.Bottom += midY;
                    canvas.DrawRect(bounds, outlinePaint);
                }
            }
            // shift y by yHeight/2 in addition to centering
            canvas.DrawIconifiedText(Icon, midX, midY+yHeight/2, iconPaint); 

![image](https://user-images.githubusercontent.com/3473919/43630619-192d2e68-9701-11e8-9bff-76522ad12929.png)

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.
