### ISSUE TITLE
rendering svg in xamarin form resulting in black square

### ISSUE THREAD

**Issue by tbelqdx** [mono/SkiaSharp.Extended#48]
I am trying to print svg pictures on my xamarin forms app. I am using SkiaSharp. I implemented a component using a Bindable property to get the byte[] of the svg and I draw it in the component.

    public static readonly BindableProperty ImageProperty = BindableProperty.Create(nameof(Image), typeof(byte[]), typeof(SvgCanvas));
    public byte[] Image
       {
          get => (byte[])GetValue(ImageProperty);
          set
         {
            if (Image == value)
            {
                return;
            }

            SetValue(ImageProperty, value);

            CanvasView.InvalidateSurface();
         }
    }

     private void OnPainting(object sender, SKPaintSurfaceEventArgs args)
     {
        SKSurface surface = args.Surface;
        SKCanvas canvas = surface.Canvas;

        int width = args.Info.Width;
        int height = args.Info.Height;

        // clear the surface
        canvas.Clear(SKColors.White);

        // the page is not visible yet
        if (Image == null)
        {
            return;
        }

        SKSvg svg = new SKSvg(new SKSize(width, height));
        using (MemoryStream ms = new MemoryStream(Image))
        {
            svg.Load(ms);
        }

        // draw the svg
       // canvas.DrawPicture(svg.Picture, ref matrix);
        canvas.DrawPicture(svg.Picture);
     }

It looks like the Picture is loaded but only a black square is displayed on my view...

My component is called like this in my page: (Picture is a byte[])

     <controls:SvgCanvas Image="{Binding Picture}" />

Did somebody had the same issue? Maybe an encoding problem?

I am kind of lost..

**Comment by mattleibow** [comment]
It may be the SVG not being properly supported. Have you tried any others?

**Comment by tbelqdx** [comment]
After some researchs not all SVG are supported. the simple ones can be displayed but others are not working at all. (for example the ones having a style)

**Comment by mattleibow** [comment]
Could you provide a link/upload to a AVG that is not working? This way we can see if we can add some of the features.

**Comment by vchelaru** [comment]
Any update on this? I'm also experiencing issues with SVGs drawing as black. For example, this does not work:

[SleepIcon.zip](https://github.com/mono/SkiaSharp.Extended/files/3614314/SleepIcon.zip)

Note Github does not support .svg files so I had to zip it first.

Expected:

![image](https://user-images.githubusercontent.com/729631/64928047-e4e62180-d7cf-11e9-849d-ab02fe8dc2a1.png)

Actual:

![image](https://user-images.githubusercontent.com/729631/64928050-efa0b680-d7cf-11e9-9a61-fe8f975233f1.png)

**Comment by jayrlsw** [comment]
I found that this issue occurred for me due to "style" elements/nodes in the SVG. Taking out the style nodes and making any styles into in-line styles fixed it for me. 

So instead of:
```
<style>.t1 {background-color: red;}</style>
<circle class="t1"></circle>
```

Try: 
```
<circle style="background-color: red;"></circle>
```

**Comment by vchelaru** [comment]
Hah thanks @jayrlsw I'm literally writing my findings at the same time as when you posted it. If it helps the development team here, Adobe Illustrator supports "Internal CSS" when exporting SVGs:

![image](https://user-images.githubusercontent.com/729631/64928323-e0236c80-d7d3-11e9-9fd0-a13bff585534.png)

This seems to not be supported. Would be a nice fix.

**Comment by maexsp** [comment]
Run into the same issue. Any updates on that?

**Comment by stntz** [comment]
> Hah thanks @jayrlsw I'm literally writing my findings at the same time as when you posted it. If it helps the development team here, Adobe Illustrator supports "Internal CSS" when exporting SVGs:
> 
> ![image](https://user-images.githubusercontent.com/729631/64928323-e0236c80-d7d3-11e9-9fd0-a13bff585534.png)
> 
> This seems to not be supported. Would be a nice fix.

Thank you for this... changing to inline style fixed my issue

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia

It has an API that is compatible and will just require a namespace change.

**Comment by vchelaru** [comment]
Thanks for that, I was worried SVG in Skia was a dead end. I'm using it
quite heavily in my projects so it's great to see active support! Loving
all your Skia work!
--Victor Chelaru--
801 391 5271
hangouts: VicChelaru@gmail.com
www.flatredball.com
