### ISSUE TITLE
FontAwesome should be updated (4.7 -> 5.3.1)

### ISSUE THREAD

**Issue by pfaucon** [mono/SkiaSharp.Extended#50]
many of the new glyphs are not available. It looks like the code should still be working, but the url has changed from:
https://raw.githubusercontent.com/FortAwesome/Font-Awesome/v4.7.0/css/font-awesome.min.css

to:
https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/web-fonts-with-css/css/fontawesome-all.min.css

**Comment by mattleibow** [comment]
I had a look and this may not be easily possible with a upgrade mindset. They have changed a fair bit: 
https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

This will need more thought:
 - do we want a new type: `FontAwesome5`
 - implement logic for case where the characters are spread across multiple font files

**Comment by pfaucon** [comment]
It seems unlikely to me that a single person will use multiple font styles in one application.  It might be reasonable then to just generate separate packages for each (like fontawesome -> FontAwesomeLight, FontAwesomeRegular...), although it would be a lot of packages.  

Another possibility would be that all of the naming seems to be the same, so perhaps the package could pack all versions and load brands always, but allow a specification of light/regular/solid at AddFontAwesome() ?

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.
