### ISSUE TITLE
Honor gradientTransform Attribute

### ISSUE THREAD

**Issue by inforithmics** [mono/SkiaSharp.Extended#53]
I discovered that gradientTransforms are not applied in SkiSharp.Extended

Current Implementation:
![image](https://user-images.githubusercontent.com/2290863/47272226-f2286b00-d582-11e8-9c28-0891cf52ae2d.png)

Improved Implementation:

![image](https://user-images.githubusercontent.com/2290863/47272216-ad9ccf80-d582-11e8-8fda-8f1564aaede6.png)

**Comment by inforithmics** [comment]
The Circular Shape has following Gradient Transform (Increasing Size)
gradientTransform="matrix(0,20.15979,40.643555,0,25.000488,26.340332)"

The Rectangular Shape has following Gradient Transform (which rotates it)
 gradientTransform="rotate(45)"

The whole file in the Pull Request, this is mainly a Test svg to display the behavior (is although used in an unit test in the pull request)
https://github.com/mono/SkiaSharp.Extended/pull/54/commits/d2dda6e5b52d3136b349d6738a74f13cea8e9a93#diff-7ce88f9ed9db78bd0491044e4fe3cbe1

**Comment by mattleibow** [comment]
Thanks for reporting this and creating a PR. I am going to merge it soon.

**Comment by mattleibow** [comment]
Merged!
