### ISSUE TITLE
When loading SVG fill="transparent" is not recognized and drawn as black

### ISSUE THREAD

**Issue by ThaDaVos** [mono/SkiaSharp.Extended#62]
I'm using SkiaSharp.Svg (1.60.0) and when drawing an SVG fill/stroke with "transparent" is not recognized and just drawn as black.

**Comment by ViceIce** [comment]
Workaround: replace `transparent` with `none`

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia

It has an API that is compatible and will just require a namespace change.
