### ISSUE TITLE
[QUESTION] What is the status of the svg nuget package?

### ISSUE THREAD

**Issue by pauldendulk** [mono/SkiaSharp.Extended#68]
There has been no new release of a 1.68 svg nuget package. 
https://www.nuget.org/packages/SkiaSharp.Svg/

The last release is of 1.60.0. There has not been a release of a 1.60.3 version. This might be because there have been no changes in the svg part, but apparently there had been breaking changes in the shared part because if upgrade to 1.60.3 and use 1.60.0 for svg we get a method not found exception in our project ([Mapsui](https://github.com/mapsui/mapsui))

Will there be a new release of the svg package?

**Comment by charlesroddie** [comment]
@mattleibow This is the svg library for cross-platform .Net use right now. It already works well. Even if not feature-complete, it does enough for most users. It's OK if you don't have time to add features. Just merging community PRs and releasing in sync with the main SkiaSharp nuget should be enough.

**Comment by mattleibow** [comment]
@charlesroddie thanks for the feedback. I hope to start doing that on a more regular basis.

**Comment by charlesroddie** [comment]
@mattleibow any ETA for Skiasharp.Svg nuget release?

**Comment by rbrian** [comment]
@mattleibow adding a voice to the request for a 1.68 compatible version. I'm suffering from a "MSB3276: Found conflicts between different versions of the same dependent assembly." problem partly because of it, AFAICT.

**Comment by claunia** [comment]
adding a voice to the request request for a 1.68 version because there have been fixes to #42  and #44

**Comment by dsyme** [comment]
I got this error when trying to use SkiaSharp for WPF 1.68.1, it might be related
```
Exception thrown: 'System.BadImageFormatException' in SkiaSharp.dll
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Exception thrown: 'System.TypeInitializationException' in SkiaSharp.Views.WPF.dll
The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
```

**Comment by charlesroddie** [comment]
@dsyme does this happen with both SkiaSharp.Svg 1.60.0 and 1.59.1?

I don't think there will be any fixes merged for SkiaSharp.Svg.

This library may be the way to go: https://github.com/wieslawsoltes/Svg.Skia . The overall project is to convert https://github.com/vvvv/SVG to netstandard (https://github.com/vvvv/SVG/issues/590) and then give it more renderers, of which https://github.com/wieslawsoltes/Svg.Skia is one.

**Comment by dsyme** [comment]
It was something else, related to this https://github.com/mono/SkiaSharp/issues/586#issuecomment-407347710

Fix is here for posterity; https://github.com/fsprojects/Fabulous/issues/619#issuecomment-558253584

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.

I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia
