### ISSUE TITLE
Empty <tspan> causes NULL reference error

### ISSUE THREAD

**Issue by jpriestley70** [mono/SkiaSharp.Extended#72]
I have a SVG where I dynamically change the text before generating it as an image.
I get a null reference error if the content of the &lt;tspan&gt;&lt;/tspan&gt; is blank.

`<text transform=""translate(400,400)"" text-anchor=""middle""><tspan style=""fill: #1A1A1A; font-family: 'Arial'; font-weight: bold; font-size: 20px;""></tspan></text>`

The work around is to put in a space.

Also get the null reference error if &lt;tspan&gt;&lt;/tspan&gt; is on a separate line to &lt;text&gt;&lt;/text&gt;

`<text transform=""translate(400,400)"" text-anchor=""middle"">`
`    <tspan style=""fill: #1A1A1A; font-family: 'Arial'; font-weight: bold; font-size: 20px;"">Some Text</tspan>`
`</text>`

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia

It has an API that is compatible and will just require a namespace change.
