### ISSUE TITLE
Cannot renderer material design icons

### ISSUE THREAD

**Issue by LeoJHarris** [mono/SkiaSharp.Extended#80]
Hi there,

I am trying to use the MaterialDesignIcons' Wrench Icon but cannot render the icon, its just saying wrench with 2 brackets on each side i.e, `{{wrench}}`:

I add below into App.xaml.cs:

```csharp
SKTextRunLookup.Instance.AddMaterialDesignIcons();
```

in my code I call:

```csharp
 canvas.DrawIconifiedText("{{wrench color=FFFFFF}}", Xc, Yc + _progressUtils.getFactoredHeight(lineHeight1), skPaint);
```

And the wrench icon I am trying to render is below:

![image](https://user-images.githubusercontent.com/5468757/59713112-be612a80-9262-11e9-906b-08d92caa24a7.png)

**Comment by LeoJHarris** [comment]
Im using latest libs for Skia sharp see below, I have also tried other material icons and they dont work either, infact I dont even get anything appear when calling

```csharp
canvas.DrawIconifiedText("{{broom color=FFFFFF}}", Xc, Yc + _progressUtils.getFactoredHeight(lineHeight3), skPaint);
```

![Capture](https://user-images.githubusercontent.com/5468757/59815362-6a426d00-936c-11e9-886d-f79e2714e79a.PNG)

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on SkiaSharp.SVG.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia 
It has an API that is compatible and will just require a namespace change.

For better text support, I again would recommend the equally awesome https://github.com/toptensoftware/RichTextKit that can pretty much do everything.

With both of these, I have updated the sample app to demonstrate how to use these libraries, producing a far better result.
