### ISSUE TITLE
Skia Sharp Extended Svg does not honor userspaceonuse in gradients

### ISSUE THREAD

**Issue by inforithmics** [mono/SkiaSharp.Extended#81]
Current Behavior

<img width="176" alt="GradientBug" src="https://user-images.githubusercontent.com/2290863/60303072-c0e41400-9935-11e9-94ee-6bf1080f8e55.PNG">

Should look like this

<img width="169" alt="GradientFixed" src="https://user-images.githubusercontent.com/2290863/60303091-cf323000-9935-11e9-8acc-859c9c15862f.PNG">

**Comment by inforithmics** [comment]
I reduced the svg to to only show the offending circle

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   width="66.666664"
   height="200"><defs>
      <radialGradient
       fx="0"
       fy="0"
       cx="0"
       cy="0"
       r="1"
       gradientUnits="userSpaceOnUse"
       gradientTransform="matrix(0,20.15979,40.643555,0,25.000488,122.98193)"
       id="radialGradient134">
          <stop style="stop-opacity:1;stop-color:#f5a8a2" offset="0"/>
          <stop style="stop-opacity:1;stop-color:#e30613" offset="0.45403363"/>
      </radialGradient>
</defs><g><path
          d="m 4.843,122.982 c 0,-11.224 9.024,-20.323 20.157,-20.323 v 0 c 11.133,0 20.158,9.099 20.158,20.323 v 0 c 0,11.225 -9.025,20.324 -20.158,20.324 v 0 c -11.133,0 -20.157,-9.099 -20.157,-20.324"
          style="fill:url(#radialGradient134)"/>
</g></svg>
```
Because of this the gradient has an absolute position
`     gradientUnits="userSpaceOnUse"`
and the gradient position shouldn't be adpated as it is currently the case

I made a pull request that fixes this. The image that I show here is already in the tests 
folder

https://github.com/mono/SkiaSharp.Extended/blob/master/SkiaSharp.Extended.Svg/tests/SkiaSharp.Extended.Svg.Tests/images/gradient.svg

**Comment by alexanderrafalovich** [comment]
I also encoutered this problem. Is there an easy way I can integrate @inforithmics fix into my project?

**Comment by inforithmics** [comment]
You could compile this code and then include it in your solution.

https://github.com/inforithmics/SkiaSharp.Extended/tree/master/SkiaSharp.Extended.Svg/source

Is only my fixes, but there are others where more bugs are fixed.

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.

I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia
