### ISSUE TITLE
Incorrect rendering of svg if SkiaSharp.svg is referenced from nuget instead of project

### ISSUE THREAD

**Issue by zoli13** [mono/SkiaSharp.Extended#88]
1. [Clicked](https://github.com/mono/SkiaSharp.Extended) on "Clone or download" > Download ZIP, unzip
2. Replace SkiaSharp.Extended.Svg\samples\SkiaSharpDemo\images\opacity.svg with the attached opacity.svg
[opacity.zip](https://github.com/mono/SkiaSharp.Extended/files/4258056/opacity.zip)
3. load SkiaSharp.Extended.Svg\SkiaSharp.Extended.Svg.sln in VS2019
4. Compile (Android only) and run SkiaSharp.Extended.Svg\samples\SkiaSharpDemo
5. It works fine

![Screenshot_1582747682](https://user-images.githubusercontent.com/9251057/75385452-0cddc300-58e0-11ea-91b7-b013ad316ae1.png)

- Now delete project dependency of SkiaSharpDemo: Dependencies>Projects>SkiaSharp.Extended.svg
- Add nuget package SkiaSharp.svg (1.60.0 - latest) for SkiaSharpDemo+SkiaSharpDemo.Droid
- Compile (you have to change 'SKSvg' -> 'SkiaSharp.Extended.Svg.SKSvg' in MainPage.xaml.cs) and run (Android).

**Result:**
Unlike before (when SkiaSharp.Extended was referenced from the project), the new opacity.svg is rendered incorrectly: sort of transparent.

![Screenshot_1582748642](https://user-images.githubusercontent.com/9251057/75385453-0d765980-58e0-11ea-911e-ff053e8093b9.png)

**Comment by zoli13** [comment]
Ok, I see there were plenty of commits to the code after the latest nuget package release (1.60.0 / 4/11/2018)
It might be the issue?

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.
I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia
