### ISSUE TITLE
Incorrect parsing of viewbox

### ISSUE THREAD

**Issue by DanAvni** [mono/SkiaSharp.Extended#89]
the svg standard says "The value of the ‘viewBox’ attribute is a list of four numbers <min-x>, <min-y>, <width> and <height>, separated by whitespace and/or a comma". The svg parser fails to read the viewbox if the value is "0, 0, 512, 512"

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.
I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia
