### ISSUE TITLE
failed to load svg on linux

### ISSUE THREAD

**Issue by e3dalive2** [mono/SkiaSharp.Extended#9]
I have svg file which i load perfectly fine on windows, but on linux(kubuntu Ubuntu 16.04.2 LTS) it fails to load specified svg file with xml parser error. It happens in canvas.DrawPath(path, fill); (path is null) on 261 line
![bug](https://user-images.githubusercontent.com/6755114/27423502-72f00e6e-573a-11e7-9b3a-bfd5f31ba501.png)
File: https://drive.google.com/file/d/0B-rAar9E1RhDNHlGVklwYXNROW8/view?usp=sharing

SkiaSharp is builded on linux by following official instructions.
Latest mono & monodevelop. Net: NetFramework 4.6.2
ParseSvgData fails on this data "M321.773,365.766 C321.773,365.766 320.899,211.818 253.571,124.348 C229.089,100.294 213.787,98.107 183.621,91.984 C228.214,90.235 253.571,86.736 288.547,124.348 C346.256,209.194 355.000,371.014 355.000,371.014 C355.000,371.014 354.126,392.007 278.929,406.877 C239.581,414.749 229.089,413.875 184.495,410.376 C291.021,397.255 321.773,365.766 321.773,365.766 Z"

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.

Thank you for all of you folks that have been using this library this long, it is always great to know that some of my work has made things a bit better. However, I am unable to maintain this library, but I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia

It has an API that is compatible and will just require a namespace change.
