### ISSUE TITLE
SVG not handing <g> tag attributes correctly.

### ISSUE THREAD

**Issue by dedmen** [mono/SkiaSharp.Extended#91]
Example SVG:
```
<svg xmlns="http://www.w3.org/2000/svg">
 <defs>
  <linearGradient id="colorSea"><stop offset="0" stop-color="#C7E6FC"/></linearGradient>
  <linearGradient id="colorForest"><stop offset="0" stop-color="#CCE699"/></linearGradient>
  <linearGradient id="colorForestBorder"><stop offset="0" stop-color="#66CC00"/></linearGradient>
 </defs>
 <rect x="0" y="0" height="1000" width="1000" fill="url(#colorSea)"/>
 <g id="forests" fill="url(#colorForest)">
  <polygon points="0,0 0,500 500,500 500,000"/>
  <g id="forestBorder" stroke="url(#colorForestBorder)">
   <line x1="000" y1="000" x2="000" y2="500"/>
   <line x1="000" y1="500" x2="500" y2="500"/>
   <line x1="500" y1="500" x2="500" y2="000"/>
   <line x1="500" y1="000" x2="000" y2="000"/>
  </g>
 </g>
</svg>
```

The polygon should get the attribute `fill="url(#colorForest)"` and the lines should get the attributes `fill="url(#colorForest)" stroke="url(#colorForestBorder)"`
g attributes should propagate down.

Expected as rendered in webbrowser on the left, actual SkiaSharp on the right

![firefox_2020-08-09_21-10-13](https://user-images.githubusercontent.com/3768165/89739895-bbd41c80-da84-11ea-8167-fb81cc85607f.png)

**Comment by dedmen** [comment]
Here is a stupid quickfix for this
https://github.com/dedmen/SkiaSharp.Extended/commit/f4a0c7e8b099fb4b10d6e7cd25996d1297e7fa5f

**Comment by mattleibow** [comment]
I would check out https://github.com/wieslawsoltes/Svg.Skia

My implementation is mostly incomplete and not really maintained. I am most probably going to remove this code or at least move it to a separate branch.

The linked implementation is pretty much complete and supports almost all svg features. It is netstandard and should work everywhere.

**Comment by dedmen** [comment]
Oh wow.. Thanks. I'm only using this via Mapsui which still uses SkiaSharp.Extended

**Comment by mattleibow** [comment]
Oh really? Maybe open an issue there and ask then to use the better svg implementation.

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.
I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia
